# Generated by Django 5.2.4 on 2025-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_question_correct_answer_question_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
