# Generated by Django 5.2.4 on 2025-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_question_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='selected_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
