# Generated by Django 5.2.4 on 2025-10-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentresponse_selected_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
