# Generated by Django 5.2.4 on 2025-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0005_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='students.course'),
        ),
    ]
